#!/bin/bash

# Exit on error
set -e

# Configuration
APP_NAME="GOST Desktop"
EXECUTABLE_NAME="GOST Desktop"
GRADLE_TASK=":composeApp:createDistributable"
BUILD_OUTPUT="composeApp/build/compose/binaries/main/app"
ARCH_BUILD_DIR="composeApp/build/arch_builds"

# Ensure we are in the project root
cd "$(dirname "$0")/.."

echo "🚀 Starting Universal macOS Build Process..."

# Cleanup
rm -rf "$ARCH_BUILD_DIR"
mkdir -p "$ARCH_BUILD_DIR"

# 1. Build for ARM64 (Apple Silicon)
# We assume the current environment is ARM64 or the default JDK is ARM64
echo "🏗️ Building for Apple Silicon (arm64)..."
./gradlew $GRADLE_TASK
mkdir -p "$ARCH_BUILD_DIR/arm64"
cp -R "$BUILD_OUTPUT/$APP_NAME.app" "$ARCH_BUILD_DIR/arm64/"

# 2. Build for x86_64 (Intel)
# This requires an Intel JDK. If not provided, we attempt to find one or fail.
# On GitHub Actions macos-latest, you might need to install it.
# For local use, we check if JAVA_HOME_X64 is set.

if [ -z "$JAVA_HOME_X64" ]; then
    echo "⚠️ JAVA_HOME_X64 is not set. Searching for an Intel JDK..."
    # Try to find an Intel JDK using java_home if available
    if command -v /usr/libexec/java_home >/dev/null 2>&1; then
        JAVA_HOME_X64=$(/usr/libexec/java_home -v 21 -a x86_64 2>/dev/null || true)
    fi
fi

if [ -z "$JAVA_HOME_X64" ] || [ ! -d "$JAVA_HOME_X64" ]; then
    echo "❌ Error: Could not find an Intel (x86_64) JDK."
    echo "   Please install an Intel JDK and set JAVA_HOME_X64."
    echo "   Example: export JAVA_HOME_X64=\$(/usr/libexec/java_home -v 21 -a x86_64)"
    exit 1
fi

echo "🏗️ Building for Intel (x86_64) using $JAVA_HOME_X64..."
JAVA_HOME="$JAVA_HOME_X64" ./gradlew clean $GRADLE_TASK

mkdir -p "$ARCH_BUILD_DIR/x86_64"
cp -R "$BUILD_OUTPUT/$APP_NAME.app" "$ARCH_BUILD_DIR/x86_64/"

# 3. Create Universal Binary
echo "💎 Creating Universal Binary..."
mkdir -p "$ARCH_BUILD_DIR/universal"
cp -R "$ARCH_BUILD_DIR/arm64/$APP_NAME.app" "$ARCH_BUILD_DIR/universal/"

# Auto-discover executable name if not set
if [ -z "$EXECUTABLE_NAME" ]; then
    EXECUTABLE_NAME=$(ls "$ARCH_BUILD_DIR/arm64/$APP_NAME.app/Contents/MacOS/" | head -n 1)
fi

echo "Merging executables for: $EXECUTABLE_NAME"

# Use lipo to merge the executables
lipo -create \
    "$ARCH_BUILD_DIR/x86_64/$APP_NAME.app/Contents/MacOS/$EXECUTABLE_NAME" \
    "$ARCH_BUILD_DIR/arm64/$APP_NAME.app/Contents/MacOS/$EXECUTABLE_NAME" \
    -output "$ARCH_BUILD_DIR/universal/$APP_NAME.app/Contents/MacOS/$EXECUTABLE_NAME"

echo "✅ Universal binary created at $ARCH_BUILD_DIR/universal/$APP_NAME.app"

# 4. Verify
echo "🔍 Verifying architectures..."
lipo -info "$ARCH_BUILD_DIR/universal/$APP_NAME.app/Contents/MacOS/$EXECUTABLE_NAME"

# 5. Package as DMG (Optional)
# This uses the createDmg task if possible, but that might overwrite.
# Better to use a tool like 'create-dmg' or just point the user to the .app
echo "📦 Packaging as DMG..."
./gradlew :composeApp:packageDmg

echo "✨ Done! Universal app is at $ARCH_BUILD_DIR/universal/$APP_NAME.app"
echo "Note: The final DMG generated by Gradle might still be arch-specific depending on how it's called."
echo "To create a truly universal DMG, you should package the 'universal' .app manually."
